// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxqnrwpncormychvgfzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4cW5yd3BuY29ybXljaHZnZnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTcxMDEsImV4cCI6MjA3MDkzMzEwMX0.W5xMJQnKPySm4e-RCouf2nwI5k1wXBJ75IPmZPz2R9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});